# Generated by Django 3.1.2 on 2020-11-09 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NBHapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
